cache:
  node:
    fields:
      - name
  async: thread
model:
  graph-entity:
    search-key: name
  embedding: 
    model-name: C:\Users\16013\.cache\modelscope\hub\iic\nlp_corom_sentence-embedding_chinese-base
    device: cpu


database:
  neo4j:
    url: bolt://localhost:7687
    database: neo4j
    username: neo4j
    # 注意数字用引号引起来
    password: TangZiYe20050316
